### ISSUE TITLE
Use Recursion to achieve O(n) complexity.

### ISSUE THREAD

**Issue by Apoorve73** [Apoorve73/Google-Coding-Interview-Solved#2]
[**Leet_Code_Challenge_2020**](https://github.com/Apoorve73/Google-Coding-Interview-Solved/blob/master/Leet_Code%20_Challenge_2020.ipynb)

**Comment by rajneesh44** [comment]
@Apoorve ```sharing the logic in C++```

int MaximumSubarray(int a[], int n){
    int local_max=0;
    int global_max= INT_MIN;
    int s=0, start=0,end=0;
    for(int i=0;i<n;i++){
        local_max = local_max+a[i];
        if(local_max<0){
            local_max=0;
            s = i+1;
        }
        else if(local_max>global_max){
            global_max = local_max;
            start = s;
            end = i;
        }
    }
    return global_max;
}

**Comment by Apoorve73** [comment]
Thank you Sir!
